#!/bin/bash
set -e

# This script is to by executed on the development machine. A copy of this script is not added to the .git repo.

Current_Dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

version_date_file="${Current_Dir}/version/current_date"
version_file="${Current_Dir}/version/current"
version="$(head -n 1 $version_file)"

version_notes_file="${Current_Dir}/version/notes"
version_notes="$(head $version_notes_file)"

echo "${version_notes}"

MESSAGE="${version_notes}"
BRANCH="$(head -n 1 version/git)"

increment_version() {

    IFS='.' read -r major minor patch <<< "$version"
    patch=$((patch + 1))

    new_version="${major}.${minor}.${patch}"

    printf "%d.%d.%d" "$major" "$minor" "$patch" > "$version_file"
    printf "$(date +%Y-%m-%d)" > "$version_date_file"
    printf "[$new_version] NOTES: " > "$version_notes_file"
    printf "#!/bin/bash
set -e

# This script is executed on the remote machine automatically after the update from GitHub is downloaded.
# Write the script (if any is required) inside the install() function below.

# NOTE:
#   The contents of this file will RESET automatically after running 'updateGit.sh'.

install() {
    # Write Update Script Here
    echo \"INSTALLING UPDATE\"
    sleep 1
    sudo systemctl restart ndpi.service
    # sudo reboot
}
install

echo \"INSTALLATION COMPLETE\"" > "sh/install-update"

}

push_to_github() {

    echo "---> Updating Local .git"
    git add .
    sleep 1
    echo "---> Commiting..."
    echo ""
    git commit -m "${MESSAGE}"

    echo ""
    echo "---> Pushing to GitHub..."
    echo ""
    sleep 1
    git push -u origin $BRANCH
    echo ""

}

echo "---> Push Patch Update to GitHub"
echo "---> Version: $version"
echo ""
sleep 1
push_to_github
sleep 1
increment_version
echo "--- COMPLETE ---"
echo "NDPi Monitor - CLIENT"
echo "v$version"
