#!/usr/bin/env bash
set -e

FADE_TIME=0.2
target=$2
current=$(amixer sget PCM | awk '/Front Left:/ {print $4; exit}')

if [[ -z "$target" ]]; then
    echo "Please provide a target volume setpoint."
    echo "Usage: $1 <LVL>"
    echo "           LVL Range: 0-255"
    exit 1
fi

if [ "$current" -lt "$target" ]; then
    while [ "$current" -lt "$target" ]; do
        current=$((current + 5))
        [ "$current" -gt "$target" ] && current=$target
        amixer set PCM "$current" >/dev/null
        sleep $FADE_TIME
    done
else
    while [ "$current" -gt "$target" ]; do
        current=$((current - 5))
        [ "$current" -lt "$target" ] && current=$target
        amixer set PCM "$current" >/dev/null
        sleep $FADE_TIME
    done
fi

exit 0