#!/usr/bin/env bash
set -e

# export DISPLAY=':0'

# xsetroot -solid '#000000' -name 'ndi_receiver_v3' &

# picom -i 0 -f --backend xrender --force-win-blend --use-damage &

# xcompmgr -d :0 -fFCnR &
# sleep 1

FADE_TIME= 0.02

fadeInVolume() {
    current=$(amixer sget PCM | awk '/Front Left:/ {print $4; exit}')
    target=255

    if [ "$current" -lt "$target" ]; then
        while [ "$current" -lt "$target" ]; do
            current=$((current + 5))
            [ "$current" -gt "$target" ] && current=$target
            amixer set PCM "$current" >/dev/null
            sleep $FADE_TIME
        done
    else
        while [ "$current" -gt "$target" ]; do
            current=$((current - 5))
            [ "$current" -lt "$target" ] && current=$target
            amixer set PCM "$current" >/dev/null
            sleep $FADE_TIME
        done
    fi
}
fadeOutVolume() {
    current=$(amixer sget PCM | awk '/Front Left:/ {print $4; exit}')
    target=0

    if [ "$current" -lt "$target" ]; then
        while [ "$current" -lt "$target" ]; do
            current=$((current + 5))
            [ "$current" -gt "$target" ] && current=$target
            amixer set PCM "$current" >/dev/null
            sleep $FADE_TIME
        done
    else
        while [ "$current" -gt "$target" ]; do
            current=$((current - 5))
            [ "$current" -lt "$target" ] && current=$target
            amixer set PCM "$current" >/dev/null
            sleep $FADE_TIME
        done
    fi
}

activateWindow() {
    WINDOW_ID="$(xdotool search --onlyvisible --class 'Chromium' | head -n 1)"

    if [[ -z "$WINDOW_ID" ]]; then
        fadeInVolume
        echo "$1 FAILED to find visible window."
        echo "---------"
        echo "[Results]"
        echo "$(xdotool search --onlyvisible --class 'chromium')"
        echo "---------"
        exit 1
    fi

    # picom -f -D 6 -i 0 --backend xrender --force-win-blend --no-fading-openclose --realtime --no-vsync &
    # picom -f -D 6 -i 0 --backend xrender --force-win-blend --realtime --vsync &
    picom --config "${HOME}/.config/picom/picom.conf" &

    sleep 0.1
    sleep 0.1
    sleep 0.1
    sleep 0.1
    sleep 0.1
    sleep 0.5
    sleep 0.5
    sleep 0.5

    xdotool windowminimize $WINDOW_ID
    sleep 0.5

    xdotool windowraise $WINDOW_ID
    sleep 0.5

    xdotool windowactivate $WINDOW_ID
}

# Start
fadeOutVolume

activateWindow

# killall picom

exit 0