#!/usr/bin/env bash

export DISPLAY=':0'

WINDOW_ID="$(xdotool search --class 'gstreamer' | head -n 1)"

xsetroot -solid '#000000'

xdotool windowminimize $WINDOW_ID
sleep 0.5
xcompmgr -d :0 -fFCnR &
sleep 1
xdotool windowraise $WINDOW_ID
sleep 0.5
xdotool windowactivate $WINDOW_ID
sleep 1
killall xcompmgr