#!/usr/bin/env bash
set -e

cd "$(dirname "${0}")/.."

BRANCH="$(head -n 1 version/git)"

git fetch origin $BRANCH

LOCAL=$(git rev-parse HEAD)
REMOTE=$(git rev-parse origin/$BRANCH)

if [ "$LOCAL" != "$REMOTE" ]; then
    git reset --hard origin/$BRANCH
    chmod +x sh/git-update
    chmod +x sh/install-update
    chmod +x sh/resolutions
    chmod +x sh/startup
    chmod +x sh/machine-info
    echo ""
    echo "PREPARING TO UPDATE"
    sleep 1
    sudo ./sh/install-update
fi

exit 0