#!/usr/bin/env bash
set -e

# cd "$(dirname "${0}")/.."
cd $HOME/TMP_ndpi

BRANCH="$(head -n 1 version/git)"

git fetch origin $BRANCH

LOCAL=$(git rev-parse HEAD)
REMOTE=$(git rev-parse origin/$BRANCH)

if [ "$LOCAL" != "$REMOTE" ]; then
    git reset --hard origin/$BRANCH

    chmod +x ./sh/*
    printf \nP
    printf R
    printf E
    printf P
    printf A
    printf R
    printf I
    printf N
    printf G
    printf " "
    printf T
    printf O
    printf " "
    printf U
    printf P
    printf D
    printf A
    printf T
    printf E\n

    ./sh/install-update
fi

exit 0