#!/usr/bin/env bash
set -e

# This script is executed on the remote machine automatically after the update from GitHub is downloaded.
# Write the script (if any is required) inside the install() function below.

# NOTE:
#   The contents of this file will RESET automatically after running updateGit.sh.

customInstallInstructions() {
    # Write Custom Update Script Here
    sleep 0.1
}

install() {
    echo "PREPARING TO INSTALL UPDATE"
    cd ../
    sleep 0.5
    local TMP="$(pwd)/TMP_ndpi"
    local PGM="$(pwd)/ndpi"
    echo "    [FROM] $TMP"
    echo "      [TO] $PGM"
    # read -rp "Install? (y/n) " confirm
    # if [[ "$confirm" = [yY] ]]; then
        sudo rsync -rvu \
          --exclude .git \
          --exclude sh/install-update \
          --exclude sh/git-update \
          "$TMP"/ "$PGM"
        sleep 0.5
        cd $PGM
        echo "$(pwd)"
        customInstallInstructions
        
        echo "Restarting NDPi Client" && sudo systemctl restart ndpi
        echo "INSTALLATION COMPLETE"
        # sudo reboot
    # else
    #     echo "INSTALLATION ABORTED"
    # fi
}


install