#!/bin/bash
set -e

# This script is executed on the remote machine automatically after the update from GitHub is downloaded.
# Write the script (if any is required) inside the install() function below.

# NOTE:
#   The contents of this file will RESET automatically after running updateGit.sh.

install() {
    # Write Update Script Here
    echo "INSTALLING UPDATE"
    sleep 1

    echo "PREPARING TO INSTALL UPDATE:"
    echo "    [FROM] ${HOME}/TMP_ndpi"
    echo "      [TO] ${HOME}/ndpi"

    read -rp "Install? (y/n) " confirm
    if [[ "$confirm" = [yY] ]]; then
        sudo rsync -vz --no-perms "${HOME}/TMP_ndpi/" "${HOME}/ndpi"
        sleep 1
        sudo systemctl restart ndpi.service
        echo "INSTALLATION COMPLETE"
        # sudo reboot
    else
        echo "INSTALLATION ABORTED"
    fi
}

install