#!/bin/bash

# This script is executed on the remote machine automatically after the update from GitHub is downloaded.
# Write the script (if any is required) inside the install() function below.

# NOTE:
#   The contents of this file will RESET automatically after running 'updateGit.sh'.

install() {
    # Write Update Script Here
    echo "INSTALLING UPDATE"
    sudo systemctl stop ndpi.service
    sleep 1
    chmod +x startup
    sudo systemctl start ndpi.service
    # sudo reboot
}
install

echo "INSTALLATION COMPLETE"