#!/usr/bin/env bash

xrandr

xrandr --listactivemonitors

# Get Current Framerate
xrandr | grep -oP '[0-9.]+(?=\*)'

# Get Prefered Framerate
xrandr | grep -oP '[0-9.]+(?=\*\+)'
xrandr | grep -oP '[0-9.]+(?=\s\+)'


exit 0