#!/usr/bin/env bash

xrandr

xrandr --listactivemonitors

# Get Current Framerate
xrandr | sed -E 's/.+ ([0-9.]+)\*.*/\1/'

# Get Prefered Framerate
xrandr | grep -oP '[0-9.]+(?=\s\+)'
xrandr | grep -oP '[0-9.]+(?=\*\+)'


exit 0