##
##
##  picom is the desktop composer tool used to manage window fade
##
##

# MUST be xrender for Raspberry Pi
backend = "xrender";

fading = true;
fade-in-step = 0.028;
fade-out-step = 0.028;

# ms between fade steps
fade-delta = 8;

# vsync FALSE; causes major video latency.
vsync = false;

realtime = true;

# Opacity
active-opacity = 1;
inactive-opacity = 0;
frame-opacity = 0;